# See: https://dart.dev/tools/pub/pubspec
name: model_viewer_plus_example
description: >-
  Demonstrates how to use the ModelViewer widget.
dependencies:
  flutter:
    sdk: flutter
  xetia_model_viewer:
    path: ../
  cupertino_icons: ^0.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.12.0 <3.0.0"
flutter:
  uses-material-design: true
  assets:
    - assets/
publish_to: none
