# See: https://dart.dev/tools/pub/pubspec
name: xetia_model_viewer
version: 0.0.1
description: >-
  A Flutter widget for rendering interactive 3D models in the glTF and GLB
  formats.
homepage: https://xetia.io
repository: https://github.com/jsc-app-2020/XETIA-Monorepo/tree/master/packages/xetia_model_viewer
publish_to: https://pub.xetia.dev

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  android_intent_plus: ^3.1.5
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.6
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  xetia_lints:
    hosted: https://pub.xetia.dev
    version: ^0.0.68

flutter:
  assets:
    - assets/
